name: Render Poster HTML

on:
  push:
    paths:
      - 'docs/poster/*.qmd'
      - 'docs/styles/*.css'
      - 'docs/figs/**'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"
      - name: Render Poster
        run: |
          quarto render docs/poster/template-poster.qmd
